
steps:
- name: 'gcr.io/cloud-builders/java/gradle'
  args: ['fatJar']
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/hello-karyon-rxnetty:$REVISION_ID", "-f", "Dockerfile", "."]
images: ['gcr.io/$PROJECT_ID/hello-karyon-rxnetty:$REVISION_ID']
images: ['gcr.io/$PROJECT_ID/hello-karyon-rxnetty:latest']